.TH "UKS" 3 "UKS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UKS
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIReadOnlyListExtensions\fP"
.br
.ti -1c
.RI "class \fBThought\fP"
.br
.RI "A \fBThought\fP is an atomic unit of thought\&. In the lexicon of graphs, a \fBThought\fP is both a "node" and an Edge\&. 
.br
 A \fBThought\fP can represent anything, physical object, attribute, word, action, feeling, etc\&. "
.ti -1c
.RI "class \fBThoughtLabels\fP"
.br
.ti -1c
.RI "class \fBUKS\fP"
.br
.RI "Contains a collection of Thoughts linked by Links to implement Common Sense and general knowledge\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for UKS from the source code\&.
