.TH "UKS.Thought" 3 "UKS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UKS.Thought \- A \fBThought\fP is an atomic unit of thought\&. In the lexicon of graphs, a \fBThought\fP is both a "node" and an Edge\&. 
.br
 A \fBThought\fP can represent anything, physical object, attribute, word, action, feeling, etc\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThought\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBThought\fP (Thought r)"
.br
.RI "Copy Constructor\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a \fBThought\fP's label OR a string represent a link or sequence\&. 
.br
 For a link, the format is "Label[From->LinkType->To]"\&. 
.br
 For a sequence, the format is "^elem1elem2elem3"\&. 
.br
 If there is a string Value associeted with this \fBThought\fP, it is added to the end of the line as "_V:value"\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.RI "Equality by label and links; treats atomic vs link appropriately\&. "
.ti -1c
.RI "\fBThought\fP \fBAddDefaultLabel\fP ()"
.br
.RI "Assigns a default label for link Thoughts when missing\&. "
.ti -1c
.RI "bool \fBHasAncestor\fP (\fBThought\fP t)"
.br
.RI "Determines whether this thought has the specified ancestor (self-inclusive)\&. "
.ti -1c
.RI "void \fBFire\fP ()"
.br
.RI "Updates the last-fired time on a \fBThought\fP\&. "
.ti -1c
.RI "\fBThought\fP \fBAddLink\fP (\fBThought\fP target, \fBThought\fP linkType)"
.br
.RI "Adds a link to a \fBThought\fP if it does not already exist\&. The \fBThought\fP is the source of the link\&. "
.ti -1c
.RI "void \fBRemoveLinks\fP (\fBThought\fP linkType)"
.br
.RI "Removes all links of a given type originating from this thought\&. "
.ti -1c
.RI "void \fBRemoveLink\fP (\fBThought\fP r)"
.br
.RI "Removes a link\&. "
.ti -1c
.RI "\fBThought\fP \fBHasLink\fP (\fBThought\fP source, \fBThought\fP linkType, \fBThought\fP targett)"
.br
.RI "Finds a link matching the optional source/type/target criteria\&. "
.ti -1c
.RI "\fBThought\fP \fBRemoveLink\fP (\fBThought\fP t2, \fBThought\fP linkType)"
.br
.RI "Removes a link of the given type to the given target\&. "
.ti -1c
.RI "\fBThought\fP \fBAddParent\fP (\fBThought\fP newParent)"
.br
.RI "Adds a parent link ("is-a") if not already present\&. "
.ti -1c
.RI "void \fBRemoveParent\fP (\fBThought\fP t)"
.br
.RI "Remove a parent from a \fBThought\fP\&. "
.ti -1c
.RI "void \fBRemoveChild\fP (\fBThought\fP t)"
.br
.RI "Remove a child link ("is-a") from this \fBThought\fP\&. "
.ti -1c
.RI "List< \fBThought\fP > \fBGetAttributes\fP ()"
.br
.RI "Gets attributes linked via "hasAttribute" or "is"\&. "
.ti -1c
.RI "bool \fBHasProperty\fP (\fBThought\fP t)"
.br
.RI "Determines whether this thought has the specified property, considering inheritance\&. "
.ti -1c
.RI "IEnumerable< \fBThought\fP > \fBEnumerateSubThoughts\fP ()"
.br
.RI "Enumerate the closure starting from this \fBThought\fP (root) using a queue (BFS): "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator Thought\fP (string label)"
.br
.RI "Allows implicit conversion from string to \fBThought\fP label lookup\&. "
.ti -1c
.RI "static bool \fBoperator==\fP (\fBThought\fP? a, \fBThought\fP? b)"
.br
.RI "Reference-based equality helper\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBThought\fP? a, \fBThought\fP? b)"
.br
.RI "Reference-based inequality helper\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DateTime \fBLastFiredTime\fP = DateTime\&.Now"
.br
.RI "Last time this thought was fired; updated by \fBFire\fP\&. "
.ti -1c
.RI "\fBThought\fP? \fB_from\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBThought\fP \fBIsA\fP\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBThought\fP > \fBLinksToWriteable\fP\fR [get]\fP"
.br
.RI "Get an "unsafe" writeable list of a \fBThought\fP's Links\&. This list may change while it is in use and so should not be used as a foreach iterator\&. "
.ti -1c
.RI "List< \fBThought\fP > \fBLinksFromWriteable\fP\fR [get]\fP"
.br
.RI "Get an "unsafe" writeable list of Links which target this \fBThought\fP\&. "
.ti -1c
.RI "IReadOnlyList< \fBThought\fP > \fBLinksTo\fP\fR [get]\fP"
.br
.RI "Full "Safe" list or links\&. "
.ti -1c
.RI "IReadOnlyList< \fBThought\fP > \fBLinksFrom\fP\fR [get]\fP"
.br
.RI "Get a "safe" list of links which target this \fBThought\fP\&. "
.ti -1c
.RI "IReadOnlyList< \fBThought\fP > \fBParents\fP\fR [get]\fP"
.br
.RI ""Safe" list of direct ancestors atomic thoughts (not links) "
.ti -1c
.RI "IReadOnlyList< \fBThought\fP > \fBChildren\fP\fR [get]\fP"
.br
.RI ""Safe" list of direct descendants "
.ti -1c
.RI "string \fBLabel\fP\fR [get, set]\fP"
.br
.RI "Manages a \fBThought\fP's label and maintais a hash table \fIRestrictions on \fBThought\fP LabelsNames: \fP"
.ti -1c
.RI "TimeSpan \fBTimeToLive\fP\fR [get, set]\fP"
.br
.RI "When set, makes a \fBThought\fP transient\&. "
.ti -1c
.RI "\fBThought\fP? \fBFrom\fP\fR [get, set]\fP"
.br
.RI "the \fBThought\fP Source "
.ti -1c
.RI "\fBThought\fP? \fBLinkType\fP\fR [get, set]\fP"
.br
.RI "The Link Type\&. "
.ti -1c
.RI "\fBThought\fP? \fBTo\fP\fR [get, set]\fP"
.br
.RI "Target of the link (if this \fBThought\fP is a link)\&. "
.ti -1c
.RI "object \fBV\fP\fR [get, set]\fP"
.br
.RI "Any serializable object can be attached to a \fBThought\fP\&. ONLY STRINGS are supported for save/restore to disk file\&. "
.ti -1c
.RI "float \fBWeight\fP\fR [get, set]\fP"
.br
.RI "Weight of this \fBThought\fP (link)\&. "
.ti -1c
.RI "IReadOnlyList< \fBThought\fP > \fBChildrenWithSubclasses\fP\fR [get]\fP"
.br
.RI "Returns direct children plus any subclass children\&. "
.ti -1c
.RI "IEnumerable< \fBThought\fP > \fBAncestorsWithSelf\fP\fR [get]\fP"
.br
.RI "Ancestors including self (BFS)\&. "
.ti -1c
.RI "IEnumerable< \fBThought\fP > \fBAncestors\fP\fR [get]\fP"
.br
.RI "Breadth-first ancestors (excluding self)\&. "
.ti -1c
.RI "IEnumerable< \fBThought\fP > \fBDescendants\fP\fR [get]\fP"
.br
.RI "Breadth-first descendants\&. "
.in -1c
.SH "Detailed Description"
.PP 
A \fBThought\fP is an atomic unit of thought\&. In the lexicon of graphs, a \fBThought\fP is both a "node" and an Edge\&. 
.br
 A \fBThought\fP can represent anything, physical object, attribute, word, action, feeling, etc\&. 

Thoughs may have labels which are any string\&.\&.\&.no special characters except '\&.'\&. Like comments or variable names, these are typically used for programmer convenience and are not usually used for functionality but are necessary to save and restore the structure\&. Labels are case-insensitive although the initial case is preserved within the \fBUKS\fP\&. Methods which return a \fBThought\fP may return null in the event no \fBThought\fP matches the result of the method\&. Methods which return lists of Thoughts will return a list of zero elements if no Thoughts match the result of the method\&. A \fBThought\fP may be referenced by its Label\&. You can write AddParent("color") [where a \fBThought\fP is a required parameter\&.] The system sill automatically retreive a \fBThought\fP with the given label\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UKS\&.Thought\&.Thought (Thought r)"

.PP
Copy Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIr\fP \fBThought\fP to copy\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBThought\fP UKS\&.Thought\&.AddDefaultLabel ()"

.PP
Assigns a default label for link Thoughts when missing\&. 
.PP
\fBReturns\fP
.RS 4
Current thought\&.
.RE
.PP

.SS "\fBThought\fP UKS\&.Thought\&.AddLink (\fBThought\fP target, \fBThought\fP linkType)"

.PP
Adds a link to a \fBThought\fP if it does not already exist\&. The \fBThought\fP is the source of the link\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP Target \fBThought\fP\&.
.br
\fIlinkType\fP Relationship type \fBThought\fP\&.
.RE
.PP
\fBReturns\fP
.RS 4
The new or existing link \fBThought\fP\&.
.RE
.PP

.SS "\fBThought\fP UKS\&.Thought\&.AddParent (\fBThought\fP newParent)"

.PP
Adds a parent link ("is-a") if not already present\&. 
.PP
\fBParameters\fP
.RS 4
\fInewParent\fP Parent to add\&.
.RE
.PP
\fBReturns\fP
.RS 4
The link thought or existing one\&.
.RE
.PP

.SS "IEnumerable< \fBThought\fP > UKS\&.Thought\&.EnumerateSubThoughts ()"

.PP
Enumerate the closure starting from this \fBThought\fP (root) using a queue (BFS): 
.IP "\(bu" 2
yields root
.IP "\(bu" 2
follows all outgoing LinksTo (includes the link-thought, its LinkType, its To)
.IP "\(bu" 2
also follows incoming "is-a" LinksFrom (includes the link-thought, its LinkType, its From) Cycle-safe via reference-identity visited set (not labels)\&.
.PP

.PP
\fBReturns\fP
.RS 4
Enumerable of sub-thoughts\&.
.RE
.PP

.SS "List< \fBThought\fP > UKS\&.Thought\&.GetAttributes ()"

.PP
Gets attributes linked via "hasAttribute" or "is"\&. 
.PP
\fBReturns\fP
.RS 4
List of attribute thoughts\&.
.RE
.PP

.SS "bool UKS\&.Thought\&.HasAncestor (\fBThought\fP t)"

.PP
Determines whether this thought has the specified ancestor (self-inclusive)\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Ancestor to test\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if found; otherwise false\&.
.RE
.PP

.SS "\fBThought\fP UKS\&.Thought\&.HasLink (\fBThought\fP source, \fBThought\fP linkType, \fBThought\fP targett)"

.PP
Finds a link matching the optional source/type/target criteria\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Optional source filter\&.
.br
\fIlinkType\fP Optional link type filter\&.
.br
\fItargett\fP Optional target filter\&.
.RE
.PP
\fBReturns\fP
.RS 4
Matching link or null\&.
.RE
.PP

.SS "bool UKS\&.Thought\&.HasProperty (\fBThought\fP t)"

.PP
Determines whether this thought has the specified property, considering inheritance\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Property thought to test\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the property is present; otherwise false\&.
.RE
.PP

.SS "implicit UKS\&.Thought\&.operator \fBThought\fP (string label)\fR [static]\fP"

.PP
Allows implicit conversion from string to \fBThought\fP label lookup\&. 
.PP
\fBParameters\fP
.RS 4
\fIlabel\fP Label to resolve\&.
.RE
.PP
\fBReturns\fP
.RS 4
The \fBThought\fP with that label or null\&.
.RE
.PP

.SS "void UKS\&.Thought\&.RemoveChild (\fBThought\fP t)"

.PP
Remove a child link ("is-a") from this \fBThought\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Child thought to remove\&.
.RE
.PP

.SS "void UKS\&.Thought\&.RemoveLink (\fBThought\fP r)"

.PP
Removes a link\&. 
.PP
\fBParameters\fP
.RS 4
\fIr\fP The \fBThought\fP's source neede not be this \fBThought\fP\&.
.RE
.PP

.SS "\fBThought\fP UKS\&.Thought\&.RemoveLink (\fBThought\fP t2, \fBThought\fP linkType)"

.PP
Removes a link of the given type to the given target\&. 
.PP
\fBParameters\fP
.RS 4
\fIt2\fP Target thought\&.
.br
\fIlinkType\fP Link type\&.
.RE
.PP
\fBReturns\fP
.RS 4
The removed link (prototype)\&.
.RE
.PP

.SS "void UKS\&.Thought\&.RemoveLinks (\fBThought\fP linkType)"

.PP
Removes all links of a given type originating from this thought\&. 
.PP
\fBParameters\fP
.RS 4
\fIlinkType\fP Link type to remove\&.
.RE
.PP

.SS "void UKS\&.Thought\&.RemoveParent (\fBThought\fP t)"

.PP
Remove a parent from a \fBThought\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP If the \fBThought\fP is not a parent, the function does nothing\&.
.RE
.PP

.SS "override string UKS\&.Thought\&.ToString ()"

.PP
Returns a \fBThought\fP's label OR a string represent a link or sequence\&. 
.br
 For a link, the format is "Label[From->LinkType->To]"\&. 
.br
 For a sequence, the format is "^elem1elem2elem3"\&. 
.br
 If there is a string Value associeted with this \fBThought\fP, it is added to the end of the line as "_V:value"\&. 
.PP
\fBReturns\fP
.RS 4
Formatted string representation\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string UKS\&.Thought\&.Label\fR [get]\fP, \fR [set]\fP"

.PP
Manages a \fBThought\fP's label and maintais a hash table \fIRestrictions on \fBThought\fP LabelsNames: \fP
.IP "\(bu" 2
must be unique
.IP "\(bu" 2
cannot include ' ' (use a - instead)
.IP "\(bu" 2
cannot include '\&.' this is the flag for creating a subclass with following attributes
.IP "\(bu" 2
cannot include '
.PP
' this is the flag for auto-increment the label
.IP "\(bu" 2
case insensitive but initial input case is preserved for display
.IP "\(bu" 2
capitalized labels are never signularized even if "singularize=true" 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for UKS from the source code\&.
