.TH "UKS.ThoughtLabels" 3 "UKS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UKS.ThoughtLabels
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBThought\fP \fBGetThought\fP (string label)"
.br
.ti -1c
.RI "static string \fBRemoveTrailingDigits\fP (string s)"
.br
.ti -1c
.RI "static string \fBAddThoughtLabel\fP (string newLabel, \fBThought\fP t)"
.br
.ti -1c
.RI "static void \fBClearLabelList\fP ()"
.br
.ti -1c
.RI "static List< \fBThought\fP > \fBAllThoughtsInLabelList\fP ()"
.br
.ti -1c
.RI "static void \fBRemoveThoughtLabel\fP (string existingLabel)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static ConcurrentDictionary< string, \fBThought\fP > \fBLabelList\fP\fR [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for UKS from the source code\&.
