.TH "UKS.UKS.sThought" 3 "UKS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UKS.UKS.sThought
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "string \fBlabel\fP = ''"
.br
.ti -1c
.RI "int \fBsource\fP = \-1"
.br
.ti -1c
.RI "int \fBlinkType\fP = \-1"
.br
.ti -1c
.RI "int \fBtarget\fP = \-1"
.br
.ti -1c
.RI "float \fBweight\fP = 1"
.br
.ti -1c
.RI "object \fBV\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for UKS from the source code\&.
